//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartaMei.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<LayoutRoot xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <RootPanel Orientation=""Horizontal"">
    <LayoutAnchorablePane DockWidth=""238"" FloatingWidth=""250"" FloatingHeight=""449"" FloatingLeft=""23"" FloatingTop=""392"">
      <LayoutAnchorable AutoHideMinWidth=""100"" AutoHideMinHeight=""100"" Title=""Objects"" IsSelected=""True"" ContentId=""CartaMei.Models.ObjectsPanelModel-Objects"" FloatingLeft=""23"" FloatingTop=""392"" FloatingWidth=""250"" FloatingHeight=""449"" LastActivationTimeStamp=""02/12/2016 11:06:49"" PreviousContainerId=""9eba6e38-8ad9-41f9-9294-85a106b3caec"" PreviousContainerIndex=""0"" />
    </LayoutAnchorablePane>
    <LayoutDocumentPane>
      <LayoutDocument Title=""test"" IsSelected=""True"" IsLastFocusedDocument=""True"" LastActivationTimeStamp=""02/12/2016 11:06:35"" />
    </LayoutDocumentPane>
    <LayoutAnchorablePane Id=""9eba6e38-8ad9-41f9-9294-85a106b3caec"" DockWidth=""250"">
      <LayoutAnchorable AutoHideMinWidth=""100"" AutoHideMinHeight=""100"" Title=""Properties"" IsSelected=""True"" ContentId=""CartaMei.Models.PropertiesPanelModel-Properties"" LastActivationTimeStamp=""02/12/2016 11:06:45"" />
    </LayoutAnchorablePane>
  </RootPanel>
  <TopSide />
  <RightSide />
  <LeftSide />
  <BottomSide />
  <FloatingWindows />
  <Hidden />
</LayoutRoot>")]
        public string Layout {
            get {
                return ((string)(this["Layout"]));
            }
            set {
                this["Layout"] = value;
            }
        }
    }
}
